version: "3.7"
services:
  vault:
    image: vault:1.4.2
    container_name: vault
    hostname: vault
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - vault-data:/vault/file/
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  vault-init:
    image: vault:1.4.2
    container_name: vault-init
    environment:
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./vault-init.sh:/usr/local/bin/vault-init.sh
      - vault-data:/vault/file/
    command: /usr/local/bin/vault-init.sh "${EMAIL}" "${PASSWORD}" "${KEY}"
    restart: on-failure
    depends_on:
      - vault
  
  attackiq:
    image: containers.cisco.com/snetlamu/attackiq-tenant-portal
    container_name: attackiq-app
    volumes:
      - vault-data:/tokens
      # - ./certs:/certs
    network_mode: service:vault
    restart: always
    depends_on:
    - vault-init

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup attackiq

volumes:
  vault-data: